#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************
Welcome!

1) to enable dev URLs, edit /root/coder/docker-compose.yaml and set DEVURL_HOST
2) to disable self-signed certificates, edit /root/coder/Caddyfile
********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF